### ISSUE TITLE
关于cookie过期问题

### ISSUE THREAD

**Issue by Darkoutput** [zouhy2001/QuantumultX_xyfy#1]
![image](https://user-images.githubusercontent.com/77570061/186279218-85f34299-26ed-43d6-b455-3b01c0f3b137.jpeg)
![image](https://user-images.githubusercontent.com/77570061/186279237-14209ed5-f3ff-421c-8841-bb212beeccfd.jpeg)
刚刚获取到的auth_code，跑打卡脚本还是提醒过期，大佬看看什么情况呀

**Comment by zouhy2001** [comment]
我的锅 你更新一下资源引用 刚刚改了个地方发自我的 iPhone在 2022年8月24日，06:47，Darkoutput ***@***.***> 写道：﻿


刚刚获取到的auth_code，跑打卡脚本还是提醒过期，大佬看看什么情况呀

**Comment by Darkoutput** [comment]
> 我的锅 你更新一下资源引用 刚刚改了个地方发自我的 iPhone在 2022年8月24日，06:47，Darkoutput ***@***.***> 写道：﻿
> 
> 
> 刚刚获取到的auth_code，跑打卡脚本还是提醒过期，大佬看看什么情况呀
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

刚看到大佬更改了，更新了下，可以了，大佬牛逼

**Comment by zouhy2001** [comment]
![IMG_0290](https://user-images.githubusercontent.com/57806936/186279856-7bbe2817-2ba6-4998-8bcb-4c755e07d4c3.jpg)
他之前的setdata 函数参数是 value key 我以为是key value

**Comment by zouhy2001** [comment]
auth_code有效期是24小时 也就是两天点一次小程序就行 手动打卡每次进去都卡空白页 这个脚本主要解决这个问题
获取到了auth_code 让他自己尝试去 Cron频率适当就行
