### ISSUE TITLE
脚本运行通知

### ISSUE THREAD

**Issue by le21888999** [zouhy2001/QuantumultX_xyfy#2]
大佬，请教一下这个脚本怎么开启弹窗通知呀？我运行了几次发现没有弹窗通知。

**Comment by zouhy2001** [comment]
> 

看日志 默认是有通知的 你看看哪里允许出错了

**Comment by zouhy2001** [comment]
> 大佬，请教一下这个脚本怎么开启弹窗通知呀？我运行了几次发现没有弹窗通知。

看看日志

**Comment by zouhy2001** [comment]
> 大佬，请教一下这个脚本怎么开启弹窗通知呀？我运行了几次发现没有弹窗通知。

![DB31F268-7618-43AA-80EF-63F37EF15523](https://user-images.githubusercontent.com/57806936/187052304-d6dea037-2382-432a-87da-b59d52d729ba.png)
![6437757C-CD8D-432E-8FBF-BAFDE5E390DC](https://user-images.githubusercontent.com/57806936/187052305-6ceaa29f-68bf-4213-b6d7-3a959446fbc8.png)

**Comment by zouhy2001** [comment]
> 大佬，请教一下这个脚本怎么开启弹窗通知呀？我运行了几次发现没有弹窗通知。

其他设置里面 要允许脚本通知 另外要给app通知权限

**Comment by le21888999** [comment]
通知权限都给了，还是没显示通知，日志有脚本运行记录

**Comment by le21888999** [comment]
![image](https://user-images.githubusercontent.com/111678392/187060232-d4363110-5427-4ce4-942d-e058b9be682d.png)

**Comment by le21888999** [comment]
但我发现打卡页面卡住了

**Comment by zouhy2001** [comment]
> 但我发现打卡页面卡住了
![Uploading 3821E66C-4627-4235-B405-F2CC14ECF443.png…]()

**Comment by zouhy2001** [comment]
![71B58746-991E-45BD-8015-9D29FAF75A82](https://user-images.githubusercontent.com/57806936/187060286-8497858e-495e-4102-8f8c-7240fabafeeb.png)

**Comment by le21888999** [comment]
![image](https://user-images.githubusercontent.com/111678392/187060362-1fc8fd1e-8295-4a87-ad73-786b40d82682.png)

**Comment by le21888999** [comment]
其他脚本有通知，就是这个打卡的出问题了

**Comment by zouhy2001** [comment]
> 其他脚本有通知，就是这个打卡的出问题了

你确定你引用了重写？

**Comment by zouhy2001** [comment]
![93CDE561-9593-4CCC-A8B0-EE50B030D9E8](https://user-images.githubusercontent.com/57806936/187060472-4facf03b-6bb0-44e6-8bef-3b72f4b9428d.jpeg)

**Comment by le21888999** [comment]
![image](https://user-images.githubusercontent.com/111678392/187060533-dd0916b0-6054-4575-9547-8f664207c886.jpeg)

**Comment by le21888999** [comment]
这个重写都会弹通知

**Comment by zouhy2001** [comment]
日志截图

**Comment by zouhy2001** [comment]
打卡不成功是不会弹通知的 打卡那个服务器有点垃圾 不是每次都能进去 只有打卡成功才会推送通知

**Comment by le21888999** [comment]
![image](https://user-images.githubusercontent.com/111678392/187060633-82a71a0f-be0e-418a-9ee7-232d653d69a5.png)

**Comment by zouhy2001** [comment]
> ![image](https://user-images.githubusercontent.com/111678392/187060633-82a71a0f-be0e-418a-9ee7-232d653d69a5.png)

今天已经用过这个脚本打卡成功了 就不会再试了。。之前就弹了通知 你估计没看到

**Comment by le21888999** [comment]
我今天是手动打卡的，打完卡才添加的脚本

**Comment by zouhy2001** [comment]
不可能每尝试一次就推送一次通知 那样太吵了
你等明天再看看吧有问题再reopen issue

**Comment by le21888999** [comment]
> ![image](https://user-images.githubusercontent.com/111678392/187060232-d4363110-5427-4ce4-942d-e058b9be682d.png)

会不会和支付宝打卡页面异常空白有关？

**Comment by le21888999** [comment]
好滴，谢谢啦

**Comment by zouhy2001** [comment]
![CEFCEF94-B524-40F0-9586-AA66E4A52B04](https://user-images.githubusercontent.com/57806936/187060852-622ec996-b687-4ecf-9eb7-d4b4afbf09c9.jpeg)
msg是推送通知和日志。log单纯只记录日志
1002是今日已打卡

**Comment by zouhy2001** [comment]
你日志肯定也没截全 issue我关了
