### ISSUE TITLE
脚本不生效

### ISSUE THREAD

**Issue by le21888999** [zouhy2001/QuantumultX_xyfy#3]
![image](https://user-images.githubusercontent.com/111678392/187564421-d5d61011-0c06-4a4d-9d8c-c7ed446ab39f.png)
大佬，脚本用不了了吗

**Comment by zouhy2001** [comment]
> ![image](https://user-images.githubusercontent.com/111678392/187564421-d5d61011-0c06-4a4d-9d8c-c7ed446ab39f.png)
> 大佬，脚本用不了了吗

更新一下脚本 定时任务都是本地文件我这改了没法同步给你们

**Comment by zouhy2001** [comment]
在考虑将配置部分和打卡部分分成两个脚本 这样打卡部分有什么改动都可以同步推送给你们

**Comment by le21888999** [comment]
好的，谢谢大佬
